theme: jekyll-theme-minimal
title: Corona Dashboard
# description: Speichere diese Seite als Bookmark und verfolge unseren Projektstand!

# your navbar links
navbar:
  - title: "Home"
    url: "/"
  - title: "Bereiche_Funktionen"
    url: "/Bereiche_Funktionen.html"
  - title: "Aufbau_Geodateninfrastruktur"
    url: "/Aufbau_Geodateninfrastruktur.html"
  - title: "Erweiterungen"
    url: "/Erweiterungen.html"
  - title: "Schnittstellen"
    url: "/Schnittstellen.html"