theme: jekyll-theme-minimal
title: Corona Dashboard
github_url: https://github.com/Aurelia-ew/4230-ProjektGeoinformatik_CoronaDashboard/tree/main
# description: Speichere diese Seite als Bookmark und verfolge unseren Projektstand!

# your navbar links
navbar:
  - title: "Home"
    url: "/"
  - title: "Bereiche_Funktionen"
    url: "/Bereiche_Funktionen.html"
  - title: "Aufbau_Geodateninfrastruktur"
    url: "/Aufbau_GID.html"
  - title: "Erweiterungen"
    url: "/Erweiterungen.html"