theme: jekyll-theme-minimal
title: Corona Dashboard
github_url: https://github.com/Aurelia-ew/4230-ProjektGeoinformatik_CoronaDashboard/tree/main
# description: Speichere diese Seite als Bookmark und verfolge unseren Projektstand!

# your navbar links
navbar:
  - title: "Home"
    url: "/"
  - title: "Bereiche und Funktionen"
    url: /Bereiche_Funktionen
    children:
      - title: Header
        url: /Funktionen_Header
      - title: Karte
        url: /Funktionen_Karte
      - title: Sidebar
        url: /Funktionen_Sidebar
      - title: Footer
        url: /Funktionen_Footer
  - title: "Aufbau der Geodateninfrastruktur"
    url: "/Aufbau_GDI"
    children:
      - title: Daten
        url: /GDI_Daten
      - title: Backend
        url: /GDI_Backend
      - title: Frontend
        url: /GDI_Frontend
      - title: Recherche
        url: /GDI_Recherche
  - title: "Erweiterungen"
    url: "/Erweiterungen"